version: '2'
services:
  postgresSQL:  #nombre de la master
    image: 'bitnami/postgresql:9.6.24'
    restart: always
    container_name: postgres-master
    volumes:
      - ./tabla.sql:/docker-entrypoint-initdb.d/tabla.sql
    
    environment:
        
        POSTGRESQL_REPLICATION_MODE: master 
        POSTGRESQL_USERNAME: postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: postgres 
        POSTGRESQL_REPLICATION_USER: postgres
        POSTGRESQL_REPLICATION_PASSWORD: postgres
    ports:
      - '5432'

  postgres-slave:
    image: 'bitnami/postgresql:9.6.24'
    restart: always
    container_name: postgres-slave
    
    environment:
        
        POSTGRESQL_REPLICATION_MODE: slave 
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_MASTER_HOST: postgresSQL
        POSTGRESQL_MASTER_PORT_NUMBER: 5432 
        POSTGRESQL_REPLICATION_USER: postgres
        POSTGRESQL_REPLICATION_PASSWORD: postgres
    depends_on:
      - postgresSQL
    ports:
      - '5432'
  

  nging_yeyoldo:
    image: nginx
    restart: always
    
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - postgresSQL

    environment:
      
      
      POSTGRES_HOST_MASTER: postgresSQL
      POSTGRES_HOST_SLAVE: postgres-slave
      
    restart: on-failure

    