version: '2'
services:
  postgresSQL:  #nombre de la master
    image: 'bitnami/postgresql:9.6.24'
    restart: always
    container_name: postgres-master
    volumes:
      - './tabla.sql:/docker-entrypoint-initdb.d/tabla.sql'
    environment:
        
        POSTGRESQL_REPLICATION_MODE: master 
        POSTGRESQL_USERNAME: user1 
        POSTGRESQL_PASSWORD: password1 
        POSTGRESQL_DATABASE: my_database 
        POSTGRESQL_REPLICATION_USER: user2 
        POSTGRESQL_REPLICATION_PASSWORD: password2 
    ports:
      - '55432:5432'

  postgres-slave:
    image: 'bitnami/postgresql:9.6.24'
    restart: always
    container_name: postgres-slave
    
    environment:
        
        POSTGRESQL_REPLICATION_MODE: slave 
        POSTGRESQL_PASSWORD: password1
        POSTGRESQL_MASTER_HOST: postgresSQL
        POSTGRESQL_MASTER_PORT_NUMBER: 5432 
        POSTGRESQL_REPLICATION_USER: user2 
        POSTGRESQL_REPLICATION_PASSWORD: password2 
    links:
       - postgresSQL
    ports:
      - '65432:5432'
  

  nging_-yeyoldo:
    image: nginx
    restart: always
    
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER1: user1
      POSTGRES_PASSWORD1: password1
      POSTGRES_USER2: user2
      POSTGRES_PASSWORD2: password2
      POSTGRES_DB: my_database
      POSTGRES_HOST_MASTER: postgresSQL
      POSTGRES_HOST_SLAVE: postgres-slave
      POSTGRES_PORT: 5432
      FLASK_ENV: development
    restart: on-failure